[package]
authors = [
    "Jorge Aparicio <jorge@japaric.io>",
    "Wink Saville <wink@saville.com",
]
edition = "2018"
name = "registers"
version = "0.2.0"

[dependencies]
aux7 = { path = "auxiliary" }
switch-hal = "0.4.0"

[dependencies.stm32f3]
version = "0.12.1"
features = ["stm32f303", "rt"]