[package]
edition = "2021"
name = "aux17"
version = "0.1.0"

[dependencies]
cortex-m = "0.6.4"
cortex-m-rt = "0.6.13"
stm32f3-discovery = "0.6.0"
panic-itm = "0.4.2"
switch-hal = "0.4.0"
stm32f3xx-hal = "0.6.1"

[dependencies.stm32f3]
version = "0.12.1"
features = ["stm32f303", "rt"]
